/*
* generated by Xtext
*/
package org.graphstream.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DGSOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
