/*
 * generated by Xtext
 */
package org.graphstream;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DGSRuntimeModule extends org.graphstream.AbstractDGSRuntimeModule {

}
