/*
* generated by Xtext
*/
package org.graphstream.ui.contentassist;

import org.graphstream.ui.contentassist.AbstractDGSProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DGSProposalProvider extends AbstractDGSProposalProvider {

}
