/*
* generated by Xtext
*/
package org.graphstream.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class DGSLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public DGSLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	/*
	String text(Header header) {
		  return "Header";
	}
	
	String text(Cg cg) {
		  return "CG";
	}*/
}
