/*
* generated by Xtext
*/
package org.graphstream;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DGSUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.graphstream.ui.internal.DGSActivator.getInstance().getInjector("org.graphstream.DGS");
	}
	
}
