/*
 * generated by Xtext
 */
package org.graphstream.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DGSUiModule extends org.graphstream.ui.AbstractDGSUiModule {
	public DGSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	    return DGSHighlightingConfiguration.class;
	  }
	 public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator(){
		 return DGSHighlightingCalculator.class;
	 }
}
